### ISSUE TITLE
get embed id

### ISSUE THREAD

**Issue by gaydba** [rutube/RutubeEmbedApi#1]
привет
а не подскажите как по линку вида https://rutube.ru/video/5fbdb8ef92282a9dce5a31daa851a03a/
получить код вида iframe width="720" height="405" src="//rutube.ru/play/embed/7135702"?

**Comment by ttyS15** [comment]
Привет!

Много полезной инфы тут http://rutube.ru/info/to_developers

Конкретно про ваш вопрос:

https://rutube.ru/api/video/5fbdb8ef92282a9dce5a31daa851a03a/?format=api

![2017-03-19_22-15-59](https://cloud.githubusercontent.com/assets/1039574/24083932/b762befe-0cf1-11e7-8709-67f7feef0834.png)

Другой способ более кошерный - oembed. Позволяет настраивать параметры получаемого эмбед-кода. (http://rutube.ru/info/to_developers#item8 и http://oembed.com)

http://rutube.ru/api/oembed/?url=https://rutube.ru/video/5fbdb8ef92282a9dce5a31daa851a03a/&format=json
